/**
 * Shared application types.
 *
 * Database-backed enums (UserRole, EventStatus, RegistrationStatus, etc.) will
 * be generated by Prisma in Phase 1 and re-exported from here so the rest of
 * the app imports them from a single place.
 */

export {};
